[versions]
kotlin = "1.9.23"
ktor-server-core = "2.3.11"

[libraries]
kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin" }
ktor-server-core = { module = "io.ktor:ktor-server-core", version.ref = "ktor-server-core" }
ktor-server-netty = { module = "io.ktor:ktor-server-netty", version.ref = "ktor-server-core" }

[plugins]

[bundles]
